<?php
/** @var \Bydn\Giftcard\Block\Adminhtml\Sales\Total\Order\Creditmemo\Create $block */
?>
<tr>
    <td class="label">
        <?php echo $block->escapeHtml(__('Refund to giftcard')) ?>
        <div id="giftcard_amount"></div>
    </td>
    <td>
        <input type="text"
               name="creditmemo[giftcard_amount]"
               value="<?php echo $block->getGiftcardAmount() ?>"
               class="input-text admin__control-text not-negative-amount"
               id="giftcard_amount" />
    </td>
</tr>
