<?php
/**
 * @package     Bydn_Giftcard
 * @author      Daniel Navarro <https://github.com/danidnm>
 * @license     GPL-3.0-or-later
 * @copyright   Copyright (c) 2025 Daniel Navarro
 *
 * This file is part of a free software package licensed under the
 * GNU General Public License v3.0.
 * You may redistribute and/or modify it under the same license.
 */
/** @var \Bydn\Giftcard\Block\Adminhtml\Sales\Total\Order\Creditmemo\Create $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<tr>
    <td class="label">
        <?= $escaper->escapeHtml(__('Refund to giftcard')) ?>
        <div id="giftcard_amount"></div>
    </td>
    <td>
        <input type="text"
               name="creditmemo[giftcard_amount]"
               value="<?= $escaper->escapeHtml($block->getGiftcardAmount()); ?>"
               class="input-text admin__control-text not-negative-amount"
               id="giftcard_amount" />
    </td>
</tr>
